### ISSUE TITLE
Training DIOR dataset

### ISSUE THREAD

**Issue by Vlad15lav** [chenyuntc/Simplified-FasterRCNN#205]
Hi, @chenyuntc. I'm training a DIOR dataset with an input size of 800x800, but my mAP value doesn't train well. Do you know what you can change in your training settings? Thanks for the answer.

**Comment by meshghi** [comment]
@Vlad15lav Hey, I'm working with DIOR dataset as well. I was wondering how could you fix the problem due to not having "difficult" objects in DIOR in comparison to PASCAL VOC? Thanks.
