### ISSUE TITLE
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

### ISSUE THREAD

**Issue by XzhWei** [chenyuntc/Simplified-FasterRCNN#234]
在jupyter运行demo时，sock.connect(sa)报错：ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
有人遇到类似问题吗？怎么解决？

**Comment by tami1082** [comment]
我也遇到了！！！绝了！

**Comment by XzhWei** [comment]
已解决！要首先在命令窗口输入python -m visdom.server打开服务器。
