### ISSUE TITLE
question about trainer.vis.plot_many(trainer.get_meter_data()),please help me

### ISSUE THREAD

**Issue by finetune-master** [chenyuntc/Simplified-FasterRCNN#238]
##### When the code runs to this senrence, it is interrupted and ipdb pops up

![faster rcnn](https://user-images.githubusercontent.com/41199078/125598905-7d310388-f354-420a-a92d-a3623e1a3e24.png)

**Comment by finetune-master** [comment]
##### I've just solve this problem

**Comment by Chinjohn** [comment]
##### delete debug folder.

**Comment by finetune-master** [comment]
##### just delete debug folder.
